/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PlainvariablesImport } from './routes/plain_variables'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PlainvariablesRoute = PlainvariablesImport.update({
  id: '/plain_variables',
  path: '/plain_variables',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/plain_variables': {
      id: '/plain_variables'
      path: '/plain_variables'
      fullPath: '/plain_variables'
      preLoaderRoute: typeof PlainvariablesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plain_variables': typeof PlainvariablesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plain_variables': typeof PlainvariablesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/plain_variables': typeof PlainvariablesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plain_variables'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plain_variables'
  id: '__root__' | '/' | '/plain_variables'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlainvariablesRoute: typeof PlainvariablesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlainvariablesRoute: PlainvariablesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/plain_variables"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/plain_variables": {
      "filePath": "plain_variables.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
